select * from customer LIMIT 20;

--1 what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2 Which customers used A discount But still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3 Which are the top five products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
Limit 5

--4 Compare the average purchase amount between standard and express shipping
select shipping_type,
ROUND(Avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5 Do subscribe customers spend more? Compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2)as avg_spend,
ROUND(SUM(purchase_amount),2)as total_revenue
from customer
group by subscription_status 
order by total_revenue, avg_spend

--6 Which five products are the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*)*100,2) as dis_rate
from customer
group by item_purchased
order by dis_rate desc
limit 5

--7 Segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment
with customer_type as(
select customer_id, previous_purchases,
CASE 
      WHEN previous_purchases = 1 THEN 'New'
	  WHEN previous_purchases bETWEEN 2 AND 10 THEN 'Returning'
	  ELSE 'Loyal'
	  END AS Customer_segment
from customer
)
Select Customer_segment, COUNT(*) as "Number of Customers"
from customer_type
Group by Customer_segment

)